version: '3.5'
services:
  backend:
    container_name: sp-account-backend
    image: "stellar-payment/sp-account-be:$BUILD_TAG"
    build: 
      context: .
      args:
        USERNAME_GITHUB: 
        TOKEN_GITHUB: 
        BUILD_TAG: $BUILD_TAG 
        BUILD_TIMESTAMP: $BUILD_TIMESTAMP
    ports:
      - "7002:7780"
    volumes:
      - /home/fuyuna/services/sp-account/data:/data
      - /home/fuyuna/services/sp-account/conf:/app/conf
      - /home/fuyuna/services/sp-account/migrations:/app/migrations
networks:
  default:
    name: stellar-net
    external: true